sudo: required
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
env:
  global:
  - secure: O81rQZUanbA8BFY6htPEeo7ay6HYzWPjXcTzCxfJ21ADDFETdp4N/eHZX3ZDZrTlcGykx3+//jtybDDO14qs56V05QRQaC3DcDNbStGG+hPD4fPv1VQicXdD25PslGPEz+qSfqSZ2dVv5hhy9hRxny9QQEjRQRFk10K3dlgzDOiH/5slEgH4H1XMnWVnPpk5Sn2EcZmRy8Gn+eWGb4SnZTg/X7QlnKcYlSfWegmoI3C7zSPH+cSpFo5kpjfzaid7HSo4yv+KJ+Lktga2Xfx10XhYtVPtA5xiVT4+CoK0dc9/045CvjdANQ1iM++bHDF71MSOUylghPRjqFOdQRBn4t/Sj6jgPUCClSui8CLwWa9zQfPQtQt/vQD8Tr+DFNVFrodtGkc4tTGSztzNb7IUiagyRI3oLVP73FSEoQsvQ6snmRZadHOcQzGJ4U8MpMz4gS1EZSqllKvUv2JtHNFAQi8PT9I2JVhYSXyXUZZPnBhSnYPdfC3t4pVJmg/RfknKaz/OWRTdOtuoQVD3A5YEPRXFQtInJBeKpurXktTDVtnsPpmObC+a+trfkkAHkqsx6bUrwLn14G6xw7EW5obsC3MdOh795TtmCnQMB7dlR1sPV3fq/xMvtE4vBokC2ZobGGQ96vvUXoPVy5xvhYh73NqI14Opv5kymDsMkQr5y7s=
  - secure: BcuYqZwT8NE3tQ5WgCu/4nsELfjX+iTjkyCpHodBCdxKKyUDsb02sFG0nYJWKFgWQMQVxx19ViKDTfWJlVSikhNnMkUqGK6yZsLgZkGlsDzAy40yuU4skVMT5hQH/5YQ0VyzRgJOH9hcz6rupMl/ty1oN6ug+kPoyGyz8+RLPtaTbRYiTHPO77wViB8oCkmUdyw20cnbvhxk78U977o4mPw2aYQesvhlnbdp/cMM8dJyDQTeOufanbtP8cJeM3jHoaEPisT/qXqDZSYU2dQr8WT4omCeIAfCSQu0IqD9Z9GJbkRhnCguCwyCgnK45j6MSTrsr2pC2T1Iro2b3gGPktjkwAs6THAjSwLd/j4TZj8WFjQwsbUi3FwifanGSiZV2iS3b4K5HPtuwpft4nTExesigfgIZmXOd3eYPxqqpCqtvlsd/lXCkfW0+l7cdn1c1GlK9PNj9bHfeJMZtFlOv9XPpxYucjQ5ffbvCCAVzlt/QyOBiG38NAjzwuZXbbzw3106QOcMQJqjGvTvQvw7zDquqDRSb7hVB5fVLNRGs7TRQdiCS4xBBBxTOmUsvIxFeCkizvl20IqsU5Qy/piO5Yaa4MMDrGL+GyDdL8cAD82wJlHtF29n5LWWREa0cbdXAmLiLLhO2hcJAbMCQeRHUznZWtWvF/4TJEJqlIpVy80=
  - secure: rOWd9d+c+xTUaMPqtSZQPCcWTIGfNyr3yc3tWqr2IgKPlUcVALrq1u+xUeRatM+CD9lABzw8B1QRrjoBrJp5+EA+iUv1wTzURp1fYHH7uj77b5YAu/qiTZ/+++sSpvpl4iwZXGn9h7E4Fhgh/xdp3dd4OhhMf2zdcHxbIMSMrJQ1HyzPAQAA8dkvpmz7x7rbhccZlGmHa6O8Kqkpdt/xs7UVxBoXQUcmR2c8AU/JVv583cFBr+sszg4lvkIV90/qsEQF7GrilA7DRrqx3yI4hjAoi0YXoVLto4C0QO1lqEPyCkB2lSt7WGsTra7B4nMFL99hAYYRmuNGP3Tu+dL2g6tQU95sGmpvU6m0UuuvHcqJ1UeU7Q9uBFSgR4X6ZE4kP/0HP35RM2yuwJmycI6oDqgXFb3PJXEt8Sv2+nKCGLoMKi1MPB7M4iDBfq6r5bdHIvtBqCHfPie9hXixP+y9ESlsievCj3hTRHBTv9YdtCtTyMgWTor8vEuDQkxkgWfzUQw012T3UZ7YyPbrCpQVUTJzWHt6n6PfEIQu3QlJzyU/H1HnsPhVrT1r14x/Qi0uhpnk/WCewDMC9qODpJqEsZ8Di3/f9nusQ5cdnzgLVGmrjEPtTo8BaI2vI2fqdChDQjKCmjkXEjmCUGFqYWbL4r94Vf/3MSIfxf1clo9L3mg=
  - CI_GPG_KEYNAME: C5544F905CA3DA7E6D6E3FA4A00AED8EE608EB39
  
before_install:
- docker pull localstack/localstack
- docker run -d -e SERVICES='sqs,sns' -p 127.0.0.1:4575:4575 -p 127.0.0.1:4576:4576
  localstack/localstack
- docker ps -a
- sleep 5
- gpg --import encrypt.keys
script:
- mvn deploy --settings target/travis/settings.xml
