### Based on the information available in http://www.debonair.io/post/maven-cd/
sudo: required
language: java
services:
- docker
cache:
  directories:
  - ~/.m2/repository
  
env:
  global:
  # CI_DEPLOY_USERNAME
  - secure: O81rQZUanbA8BFY6htPEeo7ay6HYzWPjXcTzCxfJ21ADDFETdp4N/eHZX3ZDZrTlcGykx3+//jtybDDO14qs56V05QRQaC3DcDNbStGG+hPD4fPv1VQicXdD25PslGPEz+qSfqSZ2dVv5hhy9hRxny9QQEjRQRFk10K3dlgzDOiH/5slEgH4H1XMnWVnPpk5Sn2EcZmRy8Gn+eWGb4SnZTg/X7QlnKcYlSfWegmoI3C7zSPH+cSpFo5kpjfzaid7HSo4yv+KJ+Lktga2Xfx10XhYtVPtA5xiVT4+CoK0dc9/045CvjdANQ1iM++bHDF71MSOUylghPRjqFOdQRBn4t/Sj6jgPUCClSui8CLwWa9zQfPQtQt/vQD8Tr+DFNVFrodtGkc4tTGSztzNb7IUiagyRI3oLVP73FSEoQsvQ6snmRZadHOcQzGJ4U8MpMz4gS1EZSqllKvUv2JtHNFAQi8PT9I2JVhYSXyXUZZPnBhSnYPdfC3t4pVJmg/RfknKaz/OWRTdOtuoQVD3A5YEPRXFQtInJBeKpurXktTDVtnsPpmObC+a+trfkkAHkqsx6bUrwLn14G6xw7EW5obsC3MdOh795TtmCnQMB7dlR1sPV3fq/xMvtE4vBokC2ZobGGQ96vvUXoPVy5xvhYh73NqI14Opv5kymDsMkQr5y7s=
  # CI_DEPLOY_PASSWORD
  - secure: BcuYqZwT8NE3tQ5WgCu/4nsELfjX+iTjkyCpHodBCdxKKyUDsb02sFG0nYJWKFgWQMQVxx19ViKDTfWJlVSikhNnMkUqGK6yZsLgZkGlsDzAy40yuU4skVMT5hQH/5YQ0VyzRgJOH9hcz6rupMl/ty1oN6ug+kPoyGyz8+RLPtaTbRYiTHPO77wViB8oCkmUdyw20cnbvhxk78U977o4mPw2aYQesvhlnbdp/cMM8dJyDQTeOufanbtP8cJeM3jHoaEPisT/qXqDZSYU2dQr8WT4omCeIAfCSQu0IqD9Z9GJbkRhnCguCwyCgnK45j6MSTrsr2pC2T1Iro2b3gGPktjkwAs6THAjSwLd/j4TZj8WFjQwsbUi3FwifanGSiZV2iS3b4K5HPtuwpft4nTExesigfgIZmXOd3eYPxqqpCqtvlsd/lXCkfW0+l7cdn1c1GlK9PNj9bHfeJMZtFlOv9XPpxYucjQ5ffbvCCAVzlt/QyOBiG38NAjzwuZXbbzw3106QOcMQJqjGvTvQvw7zDquqDRSb7hVB5fVLNRGs7TRQdiCS4xBBBxTOmUsvIxFeCkizvl20IqsU5Qy/piO5Yaa4MMDrGL+GyDdL8cAD82wJlHtF29n5LWWREa0cbdXAmLiLLhO2hcJAbMCQeRHUznZWtWvF/4TJEJqlIpVy80=
  # CI_GPG_KEYPASS
  - secure: N+yt/EHJW+QTRZzKWXNBOeN0eY70owdo7RtKjcth3njzh/HdNnuNYBGAOnXswBBc0fXI4O1ItH7SueQwscqOct1DAuhCgtx8aRI5OjLrPdny96AI1PYh8euplr9pEenQfEI/sfDoh0A2aemRuXXAygRhaiXnQ1zQrMa21qVyNlJZfJF7txw1/k5FkwloChjUKOCGKgOs3WiRAK4wO6MLIBbscJeElaRKSVn97fsarwimi0LBwpmVaArzYHjOWwSHTxvaujNoYDfd+LwD3satd3bDnk5sfvQ96yXaXLlEul4EMQWnQ8rY1AyoaPw9vNj3pH3O2+1WBheQxdYYJIX9NBy5Pd8MubbkaH2sJidbkkliEfjNHzP36P7aFkbZuAaKLiNm3IZJT3AgDMI7iCoCQx8r31MuuxdViiv4oXs6mT4+fn6HOjF8XjJpq/ujR78VsW7o2RU8t+D0FrCYZYA4Nj3d1eSidq49kkY1EwtMQtUjF2HbTxum7KXR+ajurUTTazQu2teMq4sCYVkZY6GAUVKty3pdXzbHSrGwVciyBApb/bMusWkrV/Ct+WcHF2eo0lXcjPvUaRj8YoVQn6GYXC2jeGZKePS6o6YgB8gMSkVHBIjObtJqlNUjyFDR8tVXktrbRe2Rb+Uxd9T8KWlL75Cn38yx9/QHA08VpHuXzrQ=
  - CI_GPG_KEYNAME: HunterCo_OSS
  
before_install:
- bash script/prepare-build.sh

install: 
- mvn install -P !release -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: 
- mvn test -P !release -B

deploy:
  - provider: script   # deploy SNAPSHOPT
    skip_cleanup: true
    script: bash scripts/deploy.sh snapshop
    on:
      branch: master
  - provider: script   # Final version
    skip_cleanup: true
    script: bash scripts/deploy.sh production
    on:
      tags: true
